### ISSUE TITLE
Webpack build error 

### ISSUE THREAD

**Issue by DrDezmond** [telenko/node-mf#3]
I took example code and tried to modify the component, but after I did it I get such an error

`webpack-cli] TypeError: The 'compilation' argument must be an instance of Compilation
    at getCompilationHooks (/Users/artemyeldinov/Documents/ProjectsEpam/kf-ng-web-light/node_modules/@telenko/node-mf/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:125:10)
    at /Users/artemyeldinov/Documents/ProjectsEpam/kf-ng-web-light/node_modules/@telenko/node-mf/node_modules/webpack/lib/javascript/CommonJsChunkFormatPlugin.js:43:19
    at Hook.eval [as call] (eval at create (/Users/artemyeldinov/Documents/ProjectsEpam/kf-ng-web-light/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/artemyeldinov/Documents/ProjectsEpam/kf-ng-web-light/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/artemyeldinov/Documents/ProjectsEpam/kf-ng-web-light/node_modules/webpack/lib/Compiler.js:1043:30)
    at /Users/artemyeldinov/Documents/ProjectsEpam/kf-ng-web-light/node_modules/webpack/lib/Compiler.js:1088:29
    at Hook.eval [as callAsync] (eval at create (/Users/artemyeldinov/Documents/ProjectsEpam/kf-ng-web-light/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/artemyeldinov/Documents/ProjectsEpam/kf-ng-web-light/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/artemyeldinov/Documents/ProjectsEpam/kf-ng-web-light/node_modules/webpack/lib/Compiler.js:1083:28)
    at /Users/artemyeldinov/Documents/ProjectsEpam/kf-ng-web-light/node_modules/webpack/lib/Compiler.js:508:12
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by telenko** [comment]
Hi @DrDezmond ,

from your error trace I see such a path for webpack:
```
node_modules/@telenko/node-mf/node_modules/webpack/lib/...
```
It means that you have webpack version conflict in your npm tree (so Node.js copied a separate webpack package inside 'node-mf').
For sure, it can be an issue. Try:
1) clean up all node_modules folder inside your project and reinstall deps again
or
2) check out if webpack version of your root project matches what 'node-mf' requests. (maybe I have to upgrade webpack in peer dependencies)

Let me know if that helps.

Thanks.

**Comment by telenko** [comment]
Closing issue due to inactivity.
